// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickScale.Models;

namespace QuickScale.Migrations
{
    [DbContext(typeof(QuickScaleDBContext))]
    partial class QuickScaleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickScale.Models.SavedFretboard", b =>
                {
                    b.Property<int>("SavedFretboardID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EighthStringNote");

                    b.Property<string>("FifthStringNote");

                    b.Property<string>("FirstStringNote");

                    b.Property<string>("FourthStringNote");

                    b.Property<string>("NinthStringNote");

                    b.Property<int>("NumberOfFrets");

                    b.Property<int>("NumberOfStrings");

                    b.Property<int?>("ScaleID");

                    b.Property<string>("SecondStringNote");

                    b.Property<string>("SeventhtringNote");

                    b.Property<string>("SixthStringNote");

                    b.Property<string>("TenthStringNote");

                    b.Property<string>("ThirdStringNote");

                    b.Property<int?>("UserID");

                    b.HasKey("SavedFretboardID");

                    b.HasIndex("ScaleID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedFretboards");
                });

            modelBuilder.Entity("QuickScale.Models.Scale", b =>
                {
                    b.Property<int>("ScaleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mode");

                    b.Property<string>("RootNote");

                    b.HasKey("ScaleID");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("QuickScale.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuickScale.Models.SavedFretboard", b =>
                {
                    b.HasOne("QuickScale.Models.Scale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleID");

                    b.HasOne("QuickScale.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
