// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickScaleAndIdentity.Models;

namespace QuickScaleAndIdentity.Migrations.QuickScaleDb
{
    [DbContext(typeof(QuickScaleDbContext))]
    partial class QuickScaleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickScaleAndIdentity.Models.SavedFretBoard", b =>
                {
                    b.Property<int>("SavedFretboardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EighthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FifthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NinthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfFrets")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfStrings")
                        .HasColumnType("int");

                    b.Property<int?>("ScaleID")
                        .HasColumnType("int");

                    b.Property<string>("SecondStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeventhtringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SixthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenthStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdStringNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SavedFretboardID");

                    b.HasIndex("ScaleID");

                    b.HasIndex("UserID");

                    b.ToTable("SavedFretBoards");
                });

            modelBuilder.Entity("QuickScaleAndIdentity.Models.Scale", b =>
                {
                    b.Property<int>("ScaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("RootNote")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ScaleId");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("QuickScaleAndIdentity.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuickScaleAndIdentity.Models.SavedFretBoard", b =>
                {
                    b.HasOne("QuickScaleAndIdentity.Models.Scale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleID");

                    b.HasOne("QuickScaleAndIdentity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
